import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
	SidebarProvider,
	Sidebar,
	SidebarTrigger,
} from "@/components/ui/sidebar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<SidebarProvider>
					<Sidebar>
						{/* Example sidebar content, replace with your navigation */}
						<nav className="p-4">
							<ul>
								<li>Home</li>
								<li>Projects</li>
								<li>About</li>
								<li>Contact</li>
							</ul>
						</nav>
					</Sidebar>
					<main>
						<SidebarTrigger />
						{/* Adjust margin for sidebar width */}
						{children}
					</main>
				</SidebarProvider>
			</body>
		</html>
	);
}
